# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Labels', '0001_initial'),
        ('Projects', '0002_auto_20160704_2042'),
        ('Global_Equipment_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipmentConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defaultLabelSize', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Custom', 'Custom')], default='Small', max_length=50)),
                ('connectionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_connection_type', to='Global_Equipment_library.GlobalConnection')),
                ('matesWith', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_mates_with', to='Global_Equipment_library.GlobalConnection')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEquipmentConnectionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_template', to='Labels.LabelTemplate')),
                ('theConnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='Project_Equipment.ProjectEquipmentConnection')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('hasMainLabel', models.BooleanField(default=True)),
                ('qtyMainLabel', models.IntegerField(default=1)),
                ('mainLabelSize', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Custom', 'Custom')], default='Small', max_length=50)),
                ('equipmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global_Equipment_library.GlobalEquipmentCategory')),
                ('globalEquipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_equipment', to='Global_Equipment_library.GlobalEquipmentItem')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global_Equipment_library.GlobalManufacturer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEquipmentPatchPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionA', to='Project_Equipment.ProjectEquipmentConnection')),
                ('connectionB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionB', to='Project_Equipment.ProjectEquipmentConnection')),
            ],
        ),
        migrations.AddField(
            model_name='projectequipmentconnection',
            name='parentEquipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parent_equipment', to='Project_Equipment.ProjectEquipmentItem'),
        ),
    ]
