# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Equipment', '0002_auto_20160704_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectequipmentitem',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
