# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Equipment_library', '0003_auto_20160704_2111'),
        ('Project_Equipment', '0003_projectequipmentitem_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectequipmentconnection',
            name='matesWith',
        ),
        migrations.AddField(
            model_name='projectequipmentconnection',
            name='matesWith',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_mates_with', to='Global_Equipment_library.GlobalConnection'),
        ),
    ]
