# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Equipment', '0004_auto_20160704_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectequipmentconnection',
            name='parentEquipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_equipment_connection', to='Project_Equipment.ProjectEquipmentItem'),
        ),
    ]
