# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0002_labeltextbox'),
        ('Project_Equipment', '0005_auto_20160704_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipmentConnectionLabelTextBox',
            fields=[
                ('labeltextbox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Labels.LabelTextBox')),
                ('parentLabelObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentLabelObject', to='Project_Equipment.ProjectEquipmentConnectionLabel')),
            ],
            bases=('Labels.labeltextbox',),
        ),
        migrations.AlterField(
            model_name='projectequipmentconnection',
            name='matesWith',
            field=models.ManyToManyField(blank=True, related_name='project_mates_with', to='Global_Equipment_library.GlobalConnection'),
        ),
    ]
