# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Equipment', '0006_auto_20160909_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectequipmentitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
