# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0002_labeltextbox'),
        ('Project_Equipment', '0007_projectequipmentitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipmentLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelTemplate', to='Labels.LabelTemplate')),
                ('theEquipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theEquipment', to='Project_Equipment.ProjectEquipmentItem')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEquipmentLabelTextBox',
            fields=[
                ('labeltextbox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Labels.LabelTextBox')),
                ('parentLabelObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Equipment.ProjectEquipmentLabel')),
            ],
            bases=('Labels.labeltextbox',),
        ),
    ]
