# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Equipment', '0008_projectequipmentlabel_projectequipmentlabeltextbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipmentSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalName', models.CharField(max_length=200)),
            ],
        ),
    ]
