# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Equipment', '0009_projectequipmentsignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEquipmentSignal',
        ),
    ]
