# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Equipment_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalequipmentitem',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
