# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Equipment_library', '0002_auto_20160704_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalequipmentconnection',
            name='matesWith',
        ),
        migrations.AddField(
            model_name='globalequipmentconnection',
            name='matesWith',
            field=models.ManyToManyField(related_name='mates_with', to='Global_Equipment_library.GlobalConnection'),
        ),
    ]
