# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Equipment_library', '0003_auto_20160704_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEquipmentBlockDiagramImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockImage', models.FileField(upload_to='GlobalEquipmentBlockDiagramImages/')),
            ],
        ),
        migrations.AddField(
            model_name='globalequipmentitem',
            name='blockDiagramImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global_Equipment_library.GlobalEquipmentBlockDiagramImage'),
        ),
    ]
