# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTextBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('font', models.CharField(choices=[('Impact', 'Impact'), ('Palatino', 'Palatino'), ('Tahoma', 'Tahoma'), ('Century Gothic', 'Century Gothic'), ('Lucida Sans Unicode', 'Lucida Sans Unicode'), ('Arial Black', 'Arial Black'), ('Times New Roman', 'Times New Roman'), ('Arial Narrow', 'Arial Narrow'), ('Verdana', 'Verdana'), ('Copperplate', 'Copperplate'), ('Lucida Console', 'Lucida Console'), ('Gill Sans', 'Gill Sans'), ('Trebuchet MS', 'Trebuchet MS'), ('Courier', 'Courier'), ('Arial', 'Arial')], max_length=100)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('fontSize', models.IntegerField(default=12)),
                ('xPoint', models.IntegerField(default=0)),
                ('yPoint', models.IntegerField(default=0)),
            ],
        ),
    ]
