# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0002_labeltextbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
