# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0001_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('emailAddress', models.EmailField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundlesLoomsMulticore', models.CharField(choices=[('Bundle', 'Bundle'), ('Loom', 'Loom'), ('Multicore', 'Multicore')], max_length=50)),
                ('UIStyle', models.CharField(choices=[('Standard', 'Standard'), ('Dark', 'Dark')], default='Standard', max_length=25)),
                ('lengthUnits', models.CharField(choices=[('feet', 'feet'), ('meters', 'meters')], max_length=20)),
                ('tagBundleEnds', models.BooleanField(default=False)),
                ('largeLabelTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_label_template', to='Labels.LabelTemplate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectSettingsProject', to='Projects.Project')),
                ('smallLabelTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_label_template', to='Labels.LabelTemplate')),
            ],
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='streetAddress2',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
