# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0003_auto_20160910_1937'),
        ('Projects', '0002_auto_20160704_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='mediumLabelTemplate',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='medium_label_template', to='Labels.LabelTemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='bundlesLoomsMulticore',
            field=models.CharField(choices=[('Bundle', 'Bundle'), ('Loom', 'Loom'), ('Multicore', 'Multicore')], default='Bundle', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='lengthUnits',
            field=models.CharField(choices=[('feet', 'feet'), ('meters', 'meters')], default='feet', max_length=20),
        ),
    ]
