# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20160910_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermissiongroup',
            name='permissionType',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('read', 'read'), ('write', 'write')], default='read', max_length=100),
        ),
    ]
